name: Mini Project JMeter API Test Action

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run JMeter Tests
      uses: rbhadti94/apache-jmeter-action@v0.5.0
      with:
        testFilePath: jmeter-api-test/MiniProjectQE_SaraLutamiPardede.jmx
        outputReportsFolder: reports/
